on:
  push:
    tags:
      - '*.*'

jobs:
  newline-test:
    name: Newline test
    runs-on: ubuntu-latest
    steps:
      - name: "test"
        run: echo docker.dev.job.dk:5111/${{ github.event.repository.name }}:${{steps.meta.outputs.tags}}
